### ISSUE TITLE
Double commit using Prettier

### ISSUE THREAD

**Issue by mmBabol** [humphd/next#32]
In order to use Prettier #7 , any files committed will need to be committed twice. This way we have the original file before prettier makes changes. We need documentation for new users on how and why to do this.

**Comment by SeanPrashad** [comment]
Could you please clarify why we need to commit files twice? I'm a little confused as to why we need the original file before Prettier makes changes - we **want** Prettier to format our code and then save that **formatted** code as part of our commits.

**Comment by dsych** [comment]
@SeanPrashad not really. We are leaving formatted files out because prettier might malformat them into invalid code. That case rarely happens, but I've seen it in action. It would be much easier for newcomers to do and extra commit compared to fixing the code that "was working before I committed and now it does not."

**Comment by dsych** [comment]
No. This PR is aimed at the following workflow:
1. You commit files.
2. Some files were formatted.
3. The commit with **unformatted** versions of the files is created.
4. Dev needs to make sure that **formatted** version of the file is working properly.
5. Commit the new version of the file.
6 Push to remote.

Speaking of formatting files on save and before commits, we can't expect all developers to use Prettier integration in their editors and if they do, not all of them will format their files on save. By checking the formats before every commit, we are insuring the consistent format regardless of the IDE or the environment.

**Comment by humphd** [comment]
There are [different workflows for using Prettier](https://prettier.io/docs/en/precommit.html), all with trade-offs.  @dsych is trying Option 4 in that list, which I think should be OK.  However, we can easily switch to another workflow if we find it doesn't work--since we're using Prettier no matter what, we'll always have a consistent code base.

I think the original comment for this bug needs to be clarified.  If someone has code that prettier changes, they should **also** commit those changes after it completes.

**Comment by humphd** [comment]
I think we can close this now, since we use it via eslint.
