### ISSUE TITLE
Create Dockerfile to run BuildRoot

### ISSUE THREAD

**Issue by humphd** [humphd/next#57]
We want to experiment with using [BuildRoot](https://buildroot.org/downloads/Vagrantfile) to build a custom Linux VM for the browser.  Let's create a [Dockerfile](https://docs.docker.com/engine/reference/builder/) and use Docker, so our Windows friends can play along too.

Here is the Vagrantfile that BuildRoot uses, which should guide us:

https://buildroot.org/downloads/Vagrantfile

**Comment by dsych** [comment]
The is a problem with docker containers where the config menu for buildroot shows up broken like so:
![menuconfig](https://user-images.githubusercontent.com/16144679/40589605-fd5d348a-61bd-11e8-8786-6cb13d42a929.png)
It seems to be a problem with locales where it wont display UTF-8 characters even though locale is set to `C.UTF-8`.
The good news is, that we can still work with the [Vagrantfile](https://buildroot.org/downloads/Vagrantfile) as it seems to be working properly. In my opinion, we can just stick to vagrant, since I don't think this is worth spending too much time on.
cc @twigz20 @mmBabol @Fatehsandhu

**Comment by dsych** [comment]
Update, I was able to solve the problem by running an ssh server on a container and using ssh connection to get shell inside the container.

**Comment by humphd** [comment]
This landed in #83
